### ISSUE TITLE
18和非18能不能分两个路径存放

### ISSUE THREAD

**Issue by MoKeNeng** [Special-Week/youth-version-of-setu4#4]
如果能让两种图片分开存放，以后用也好用一点(✿◡‿◡)

**Comment by MoKeNeng** [comment]
解决了

**Comment by Special-Week** [comment]
> 解决了

正好我也懒得动了, 代码该打的注释都打上了, 想自己自定义随意

**Comment by MoKeNeng** [comment]
谢谢你，不过大佬你有个巨离谱的地方，判断是否18不是布尔类型，是字符串类型，让我研究半天不知道哪里出问题了。

**Comment by Special-Week** [comment]
> 谢谢你，不过大佬你有个巨离谱的地方，判断是否18不是布尔类型，是字符串类型，让我研究半天不知道哪里出问题了。

设计数据表时候的缺陷，也一直懒得修了
