### ISSUE TITLE
使用nb安装未找到包

### ISSUE THREAD

**Issue by tiantianbetter** [Special-Week/youth-version-of-setu4#5]
包youth-version-of-setu4未找到是为什么呀![Screenshot_2023-02-01-09-16-00-068_com.termux-edit.jpg](https://user-images.githubusercontent.com/44676131/215921262-0bb3d05d-d8d5-4b70-a062-30fc3dd94581.jpg)

**Comment by Special-Week** [comment]
我没上传到nb商店, nb商店有完整版的了, 这个只是我不想搞权限配置阉割了的

**Comment by tiantianbetter** [comment]
> 我没上传到nb商店, nb商店有完整版的了, 这个只是我不想搞权限配置阉割了的

好的，感谢大佬！我是看了那个完整版本来这的
